### PR TITLE
Support IE Mobile

### PR DESCRIPTION
**Pull request by ChickenMythic**
Support IE Mobile (Windows Phone 8.1+)

### CODE REVIEW

**Comment by pmuellr** [comment]
Is there an issue open for this at Jira?  You can open one [here](https://issues.apache.org/jira/secure/CreateIssueDetails!init.jspa?pid=12312420&components=12316604&priority=3&issuetype=1), or I can create one.  

The issue - or description of the issue here that I will create - should provide some information about why this is needed.  Eg, which browser version, library, etc does this new user agent show up in?

**Comment by ChickenMythic** [comment]
There is no issue opened for this at Jira, you create one if you want to, I won't do it.

Here is the issue description:
We've used weinre library and the code is executed in webview on various mobile platforms (iOS, Android and WindowsPhone). It works fine on iOS and Android but not on WindowsPhone as IE (11) does not support overriding of standard storage functions.
All values set as storage properties are cast to String. As a result, localStorage getItem, setItem and removeItem functions are no more functions and thus, we can no longer use localStorage once weinre got initialized.
By digging into our code, it led us to weinre library code, then we found it came from this line un "_weinre.web/modules/weinre/common/HookLib.coffee_".
The test originally made to avoid this issue on IE was made for the Desktop version of IE but did not take the Mobile version into account that's why I just suggested to add "IEMobile" to this condition.

WindowsPhone uses a slightly different version of IE 11.


Let me know if you think this fix is appropriate.

**Comment by pmuellr** [comment]
@sgrebnov I believe you added this bit of code way back when; anything else we need to look out for here?

**Comment by pmuellr** [comment]
I've opened https://issues.apache.org/jira/browse/CB-10886

Also, just wanted to let you know there are better tools than weinre available now.  Info here, but honestly not sure what the state of debug on Windows phones is currently:

http://people.apache.org/~pmuellr/weinre/docs/latest/

**Comment by ChickenMythic** [comment]
Thank you.

You're right for WindowsPhone (for example), Visual Studio is well suited to debuggued webviews but it actually requires to use Visual Studio itself. Our web dev work on Unix machines and use Weinre for remote debugging. This way they can debug the same webview piece of code executed on different webview from different mobile platforms.

**Comment by jcesarmobile** [comment]
Thanks for the PR, but we are deprecating weinre and we won't do more releases, so we won't merge this. Sorry

**Pull request closed without merging**
