### PR TITLE
`func` sometimes is undefined

### PR DESCRIPTION
**Pull request by wuchangming**
This will cause weinre crash.

### CODE REVIEW

**Comment by pmuellr** [comment]
Thanks for the PR!

Same comment as I left in #11 ...

Is there an issue open for this at Jira?  You can open one [here](https://issues.apache.org/jira/secure/CreateIssueDetails!init.jspa?pid=12312420&components=12316604&priority=3&issuetype=1), or I can create one.  

The issue - or description of the issue here that I will create - should provide an example where this breaks, so we can better understand the problem.

**Comment by wuchangming** [comment]
@pmuellr , It's because `Error.prepareStackTrace` is global scope.
when I integrate `weinre` in my project, some awful happens in my OWN program and cause a 
connect error: 
```
"Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)"
```

then the code `Error.prepareStackTrace` will called. 

**utils.js**
```
Line 176    func = callSite.getFunction(); // func = undefined
```

It's not fair to blame this bug to `weinre`, but It's effect my program indeed.

Any good advice?

**Comment by pmuellr** [comment]
Weinre isn't really built to be integrated into another program, directly.  It's really meant to be used stand-alone.

What are you trying to do?

The Error.prepareStackTrace can be removed, I think.  I don't think it has anything to do with weinre functionality, it just provides nicer looking stack traces for errors.  Very curious that that code ran into a function which wasn't a function.  Something else monkeying with Error.prepareStackTrace.

In any event, that won't fix your actual problem, which I don't yet understand.

Also want to make sure you still need to use weinre - many people don't, since the mobile debuggers have improved greatly over the years.  See the "Do you need to use weinre?" yellow section of this page - http://people.apache.org/~pmuellr/weinre/docs/latest/

**Comment by wuchangming** [comment]
I fixed this issue with trick in my program:
```
const weinre = require('weinre');
var temPrepareStackTrace = Error.prepareStackTrace;
Error.prepareStackTrace = (error, structuredStackTrace) => {
    try {
        temPrepareStackTrace(error, structuredStackTrace);
    } catch (e) {
        console.error(e);
    }
}
```

Actually, I really need `weinre`, I'm trying to build an easy tool (a proxy) for page debug in any scene ,Browser or Webview without extra configure.

LOL, I just mean `callSite.getFunction()` sometimes will get an `undefined`, such as the Socket CONNECT Error I met.
**utils.js**
```
Line 176    func = callSite.getFunction(); // func = undefined
....
Line 183    funcName = func.displayName || func.name || callSite.getFunctionName();  //  so an error occur here
```

**Comment by pmuellr** [comment]
So the ECONNREFUSED error you're seeing doesn't have anything to do with weinre?  I'm worried the Error.prepareStackTrace was just the immediate symptom, that the actual problem was with the ECONNREFUSED.

I'd like to understand your use case a bit more, because, as I noted above, weinre wasn't really designed to be used as a library, just as a standalone.  There may be other issues regarding the way you've integrated weinre as a library.

**Comment by wuchangming** [comment]
Finally, I found that there was noting wrong with weinre.

My use case is integrated a proxy for mobile device, that the proxy inject a `script tag` that what weinre need in every HTML file,Making use weinre become more easy. [spy-debugger](https://github.com/wuchangming/spy-debugger)

**Pull request closed without merging**
